services:
  ai-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: monitor-vehicle-ee-ai:latest
    container_name: monitor-vehicle-ee-ai
    ports:
      - "8001:8001"
    environment:
      DEVICE: "cpu"
      CAMERA_API_URL: "http://host.docker.internal:8000"
      AI_PUBLIC_URL: "http://localhost:8001"
      VIDEO_BASE_DIR: "/app/dataset/vehicle/videos"
      OUTPUT_DIR: "/app/dataset/output_test"
      EVENT_IMAGES_DIR: "/app/dataset/output_test/events"
      STREAM_WIDTH: "640"
      JPEG_QUALITY: "75"
      SHOW_WINDOW: "false"
    volumes:
      - ./model:/app/model:ro
      - ./dataset/vehicle/videos:/app/dataset/vehicle/videos:ro
      - ./dataset/output_test:/app/dataset/output_test
    restart: unless-stopped
